### ISSUE TITLE
don't work 

### ISSUE THREAD

**Issue by root-deeptown** [1ucif3r/aircrackauto#1]
─[root@1ucif3r]──[~]─[Menu]:
└─────► 1

[Selected] Option 1 Wifi Hacking...
ioctl(SIOCGIFINDEX) failed: No such device
[wlan0mon] Preparing for scan...
./aircrackauto.sh: строка 147: kill: (96664) - Нет такого процесса
sed: невозможно прочитать generated-01.kismet.csv: Нет такого файла или каталога

SerialNo        WiFi Network
cut: generated-01.kismet.csv: Нет такого файла или каталога
wc: generated-01.kismet.csv: Нет такого файла или каталога
./aircrackauto.sh: строка 153: [: 1000: ожидается унарный оператор
./aircrackauto.sh: строка 157: generated-01.kismet.csv: Нет такого файла или каталога
./aircrackauto.sh: строка 158: generated-01.kismet.csv: Нет такого файла или каталога
./aircrackauto.sh: строка 159: generated-01.kismet.csv: Нет такого файла или каталога

[] Preparing for attack...
[wlan0mon] Sending DeAuth to target...
[Input] Path to wordlist (Press enter to use default): 
[Status] Waiting for Handshake Packet...
[Status] Checking for Handshake Packet...
[!] Can't find Handshake, waiting ...
[Status] Checking for Handshake Packet...
[!] Can't find Handshake, waiting ...
[Status] Checking for Handshake Packet...
[!] Can't find Handshake, waiting ...
[Status] Checking for Handshake Packet...
[!] Can't find Handshake, waiting ...
[Status] Checking for Handshake Packet...
[!] Can't find Handshake, waiting ...
[Status] Checking for Handshake Packet...
[!] Can't find Handshake, waiting ...
[Status] Checking for Handshake Packet...
./aircrackauto.sh: строка 92: kill: (96870) - Нет такого процесса
rm: невозможно удалить 'handshake-01.cap': Нет такого файла или каталога
[!] Unknown error is occured...
[GitHub] You can discuss at https://github.com/1ucif3r/aircrakauto/discussions
[GitHub] Do paste content of password and error log files...

**Comment by 1ucif3r** [comment]
it's a very old let me check and update it . Thanks for reporting  me
